<?php

/**
 * PluginGoogleAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfGoogleLoginPlugin
 * @subpackage model
 * @author     Sebastian Herbermann <sebastian.herbermann@googlemail.com>
 */

class PluginGoogleAccount extends BaseGoogleAccount
{
}
